version: "3.8"

services:
  backend-db:
    image: postgres:alpine
    container_name: backend-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dealership
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
      - ./db/0_postgres.conf:/var/lib/postgresql/data/postgresql.conf
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf
  flask-app:
    build:
      context: .
    container_name: flask-app
    restart: always
    ports:
      - "718:5000"  # Flask default port is 5000
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@backend-db:5432/dealership
    depends_on:
      - backend-db  # Ensures the database starts first

volumes:
  postgres-data: