version: "3.8"
services:
  backenddb:
    image: 	postgres:alpine
    restart: always
    ports:  
        - 80:5432
    environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=dealership
    volumes:
      - ./:/docker-entrypoint-initdb.d/